CREATE TABLE `invoiec_products` (
    `id` BIGINT(50) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
   
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    FOREIGN KEY(`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,

    `product_id` BIGINT(50) UNSIGNED NOT NULL,
    FOREIGN KEY(`product_id`) REFERENCES `products`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,

    `invoiec_id` BIGINT(50) UNSIGNED NOT NULL,
    FOREIGN KEY(`invoiec_id`) REFERENCES `invoiecs`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,

    `qty` VARCHAR(50) NOT NULL,
    `sale_price` VARCHAR(50) NOT NULL,

    
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
   
)